version: "3.9"

services:
  webapi:
    build:
      context: ..
      dockerfile: EchoServiceApi/Dockerfile
      args:
        VERSION: 1.0.1-dev
    image: netlah/echo-service-api:nanoserver-1809-5.0.9
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - Serilog__MinimumLevel__Override__Serilog.AspNetCore.RequestLoggingMiddleware=Information
      - Serilog__MinimumLevel__Override__Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware=Debug
