trigger:
  branches:
    include:
      - main
  tags:
    include:
      - "*.*.*"

pr:
  - main

variables:
  buildConfiguration: "Release"

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 6.x"
    inputs:
      version: 6.x

  - script: dotnet --info
    displayName: "dotnet info"

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: "dotnet build $(buildConfiguration)"

  - script: dotnet publish EchoServiceApi -o ./artifacts/echoServiceApi/ --configuration $(buildConfiguration) --no-build
    displayName: "dotnet publish $(buildConfiguration)"
