trigger:
  branches:
    include:
      - main
      - dev*
  tags:
    include:
      - "*.*.*"

pr:
  - main

variables:
  buildConfiguration: "Release"

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macos-latest"
    windows:
      imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 8.x"
    inputs:
      version: 8.x
      includePreviewVersions: true

  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 7.x"
    inputs:
      version: 7.x

  - task: UseDotNet@2
    displayName: "Use .NET Core sdk 6.x"
    inputs:
      version: 6.x

  - script: dotnet --info
    displayName: "dotnet info"

  - script: dotnet build --configuration $(buildConfiguration)
    displayName: "dotnet build $(buildConfiguration)"

  - script: |
      dotnet publish EchoServiceApi --configuration $(buildConfiguration) --no-build -f net6.0 --no-build -o artifacts/net6.0/app
      dotnet publish EchoServiceApi --configuration $(buildConfiguration) --no-build -f net7.0 --no-build -o artifacts/net7.0/app
      dotnet publish EchoServiceApi --configuration $(buildConfiguration) --no-build -f net8.0 --no-build -o artifacts/net8.0/app
    displayName: "dotnet publish $(buildConfiguration)"
