version: "3.9"

services:
  webapi:
    build:
      context: .
      dockerfile: EchoServiceApi/Dockerfile
    image: netlah/echo-service-api:linux
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - Serilog__MinimumLevel__Override__Serilog.AspNetCore.RequestLoggingMiddleware=Information
      - Serilog__MinimumLevel__Override__Microsoft.AspNetCore.HttpOverrides.ForwardedHeadersMiddleware=Debug
